services:
  db:
    image: docker.io/library/postgres:15
    environment:
      POSTGRES_DB: kubsu
      POSTGRES_USER: kubsu
      POSTGRES_PASSWORD: kubsu
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8090 --reload
    volumes:
      - ./src:/app/src
    environment:
      DATABASE_URL: postgresql+psycopg://kubsu:kubsu@db:5432/kubsu
    ports:
      - "8090:8090"
    depends_on:
      - db

volumes:
  postgres_data: