# Билдер
FROM python:3.11-slim AS builder

WORKDIR /app

# Установка зависимостей для сборки
RUN apt-get update && apt-get install -y build-essential

# Создание виртуального окружения
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Копирование зависимостей
COPY pyproject.toml .

# Установка зависимостей
RUN pip install --no-cache-dir .[test]

# Копирование исходного кода
COPY . .

# Финальный образ
FROM python:3.11-slim

# Установка runtime зависимостей
RUN apt-get update && apt-get install -y libpq5 && rm -rf /var/lib/apt/lists/*

# Копирование виртуального окружения
COPY --from=builder /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Копирование исходного кода
COPY src /app/src
WORKDIR /app

# Переменные окружения по умолчанию
ENV APP_PORT=8000
ENV DB_USER=kubsu
ENV DB_PASSWORD=kubsu
ENV DB_HOST=127.0.0.1
ENV DB_PORT=5432
ENV DB_NAME=kubsu

# Открытие порта
EXPOSE $APP_PORT

# Команда запуска
CMD ["sh", "-c", "uvicorn src.main:app --host 0.0.0.0 --port ${APP_PORT}"]
