services:
  app:
    build: .
    ports:
      - "60080:8000"  # Используйте порт из задания
    environment:
      DB_HOST: postgres
      DB_USER: kubsu
      DB_PASSWORD: kubsu
      DB_NAME: kubsu
      DB_PORT: 5432
    depends_on:      
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: kubsu
      POSTGRES_PASSWORD: kubsu
      POSTGRES_DB: kubsu
    ports:
      - "5433:5432"  # Изменяем внешний порт на 5433
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kubsu -d kubsu"]
      interval: 5s
      timeout: 5s
      retries: 5
