services:
  db:
    image: docker.io/library/postgres:15-alpine
    environment:
      POSTGRES_DB: kubsu
      POSTGRES_USER: kubsu
      POSTGRES_PASSWORD: kubsu
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile.minimal
    environment:
      DATABASE_URL: postgresql+psycopg://kubsu:kubsu@db:5432/kubsu
    ports:
      - "8090:8090"
    depends_on:
      - db

volumes:
  postgres_data: 